create table if not exists temp_countries
(
    cca3              varchar(3) not null primary key,
    cca2              varchar(2),
    ccn3              integer,
    cioc              varchar(50),
    independent       boolean,
    status            varchar(30),
    un_member         boolean,
    name_common       varchar(100),
    name_official     varchar(100),
    native_name       jsonb,
    region            varchar(100),
    subregion         varchar(100),
    capital           varchar(100),
    lat               numeric(15, 8),
    lng               numeric(15, 8),
    capital_lat       numeric(15, 8),
    capital_lng       numeric(15, 8),
    tld               varchar(50),
    area              numeric(15, 2),
    population        numeric(15, 2),
    landlocked        boolean,
    start_of_week     varchar(50),
    timezones         jsonb,
    continents        jsonb,
    borders           jsonb,
    currency          varchar(50),
    currency_name     varchar(100),
    currency_symbol   varchar(50),
    languages         jsonb,
    translations      jsonb,
    prefix            varchar(50),
    suffix            varchar(50),
    car_sign          varchar(50),
    car_side          varchar(50),
    google_maps       text,
    open_street_maps  text,
    postal_code       jsonb,
    flags_json        jsonb,
    flag_svg_url      text,
    flag_png_url      text,
    coat_of_arms_json jsonb,
    coat_svg_url      text,
    coat_png_url      text,
    flag_emoji        text,
    flag_svg          bytea,
    flag_png          bytea,
    coat_svg          bytea,
    coat_png          bytea
);

alter table temp_countries
    owner to enargit_quartz;
grant delete, insert, references, select, trigger, truncate, update on temp_countries to postgis;
grant select on temp_countries to enargit_quartz_anon;